# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1st7k6CI3w0mZ2GF-MVfLPF2O9EZ5xneT
"""

import random


minimum = 1
maximum = 100
answer = ""
playing = ""




while playing != "yes":
  while answer != "no":
    n = random.randint(minimum,maximum)
    print("is " +str(n) + " your number?")
    print("Answer with yes, low, or high")
    answer = input()


    if answer == "high":
      maximum = n-1
      n = random.randint(minimum,maximum)
    elif answer == "low":
      maximum = n+1
      n = random.randint(minimum,maximum)
    elif answer == "yes":
      print("I guessed right! do you want to play again? answer with yes or no")
      answer = ""
      playing = input()
      if playing == "no":
        break
        
    else:
      print("please answer correctly")
      continue

